# Generated by Django 6.1 on 2026-08-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=20)),
                ('goal', models.TextField(blank=True)),
                ('modules', models.JSONField(default=list)),
                ('xp_total', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
