# Generated by Django 6.1 on 2026-08-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='checkins',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='completed',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='last_checkin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
