# Generated by Django 6.1 on 2026-08-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_roadmap_checkins_roadmap_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='resources',
            field=models.JSONField(default=list),
        ),
    ]
