# Generated by Django 6.1 on 2026-08-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_roadmap_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='final_challenge',
            field=models.JSONField(default=dict),
        ),
    ]
