# Generated by Django 6.1 on 2026-08-26 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='email', max_length=20)),
                ('avatar_url', models.URLField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('gemini_api_key', models.CharField(blank=True, max_length=200)),
                ('usage_date', models.DateField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
